version: "3.7"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/home/app/web
    ports:
      - 5678:5678
      - 8001:8001 # mapped to 8001 to prevent clashes with local django instances
      - 3000:3000 # debugger
    env_file:
      - ./.env
    environment:
      - DB_NAME=admg_webapp
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - MIGRATE=true
      - DJANGO_DEBUG_TOOLBAR=1
      - DJANGO_DEBUGGER=1
    depends_on:
      - db

  db:
    image: postgis/postgis:12-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admg_webapp
    ports:
      - 5432:5439

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  celery_worker:
    build:
      context: ./
      dockerfile: Dockerfile.local
    command: celery -A config worker -l info
    container_name: celery_worker
    hostname: celery_worker
    volumes:
      - .:/home/app/web
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - DB_NAME=admg_webapp
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - MIGRATE=false
    depends_on:
      - web
      - rabbitmq

volumes:
  postgres_data:
  static_volume:
  media_volume:
